import LrxLean.Defs

/-! Generated by autoresearch/lean-loop-260925/gen_conformance.py from
src/lrx/state.py (apply_L, apply_R, apply_X, canonical_root, remove_zero_at). Do not edit. -/
namespace LRX.Conformance
open LRX

example : exec [] [1, 2, 3, 0, 0] = [1, 2, 3, 0, 0] := rfl
example : exec [.L] [1, 2, 3, 0, 0] = [2, 3, 0, 0, 1] := rfl
example : exec [.R] [1, 2, 3, 0, 0] = [0, 1, 2, 3, 0] := rfl
example : exec [.X] [1, 2, 3, 0, 0] = [2, 1, 3, 0, 0] := rfl
example : exec [.L, .L] [1, 2, 3, 0, 0] = [3, 0, 0, 1, 2] := rfl
example : exec [.L, .R] [1, 2, 3, 0, 0] = [1, 2, 3, 0, 0] := rfl
example : exec [.L, .X] [1, 2, 3, 0, 0] = [3, 2, 0, 0, 1] := rfl
example : exec [.R, .L] [1, 2, 3, 0, 0] = [1, 2, 3, 0, 0] := rfl
example : exec [.R, .R] [1, 2, 3, 0, 0] = [0, 0, 1, 2, 3] := rfl
example : exec [.R, .X] [1, 2, 3, 0, 0] = [1, 0, 2, 3, 0] := rfl
example : exec [.X, .L] [1, 2, 3, 0, 0] = [1, 3, 0, 0, 2] := rfl
example : exec [.X, .R] [1, 2, 3, 0, 0] = [0, 2, 1, 3, 0] := rfl
example : exec [.X, .X] [1, 2, 3, 0, 0] = [1, 2, 3, 0, 0] := rfl
example : exec [.L, .L, .L] [1, 2, 3, 0, 0] = [0, 0, 1, 2, 3] := rfl
example : exec [.L, .L, .R] [1, 2, 3, 0, 0] = [2, 3, 0, 0, 1] := rfl
example : exec [.L, .L, .X] [1, 2, 3, 0, 0] = [0, 3, 0, 1, 2] := rfl
example : exec [.L, .R, .L] [1, 2, 3, 0, 0] = [2, 3, 0, 0, 1] := rfl
example : exec [.L, .R, .R] [1, 2, 3, 0, 0] = [0, 1, 2, 3, 0] := rfl
example : exec [.L, .R, .X] [1, 2, 3, 0, 0] = [2, 1, 3, 0, 0] := rfl
example : exec [.L, .X, .L] [1, 2, 3, 0, 0] = [2, 0, 0, 1, 3] := rfl
example : exec [.L, .X, .R] [1, 2, 3, 0, 0] = [1, 3, 2, 0, 0] := rfl
example : exec [.L, .X, .X] [1, 2, 3, 0, 0] = [2, 3, 0, 0, 1] := rfl
example : exec [.R, .L, .L] [1, 2, 3, 0, 0] = [2, 3, 0, 0, 1] := rfl
example : exec [.R, .L, .R] [1, 2, 3, 0, 0] = [0, 1, 2, 3, 0] := rfl
example : exec [.R, .L, .X] [1, 2, 3, 0, 0] = [2, 1, 3, 0, 0] := rfl
example : exec [.R, .R, .L] [1, 2, 3, 0, 0] = [0, 1, 2, 3, 0] := rfl
example : exec [.R, .R, .R] [1, 2, 3, 0, 0] = [3, 0, 0, 1, 2] := rfl
example : exec [.R, .R, .X] [1, 2, 3, 0, 0] = [0, 0, 1, 2, 3] := rfl
example : exec [.R, .X, .L] [1, 2, 3, 0, 0] = [0, 2, 3, 0, 1] := rfl
example : exec [.R, .X, .R] [1, 2, 3, 0, 0] = [0, 1, 0, 2, 3] := rfl
example : exec [.R, .X, .X] [1, 2, 3, 0, 0] = [0, 1, 2, 3, 0] := rfl
example : exec [.X, .L, .L] [1, 2, 3, 0, 0] = [3, 0, 0, 2, 1] := rfl
example : exec [.X, .L, .R] [1, 2, 3, 0, 0] = [2, 1, 3, 0, 0] := rfl
example : exec [.X, .L, .X] [1, 2, 3, 0, 0] = [3, 1, 0, 0, 2] := rfl
example : exec [.X, .R, .L] [1, 2, 3, 0, 0] = [2, 1, 3, 0, 0] := rfl
example : exec [.X, .R, .R] [1, 2, 3, 0, 0] = [0, 0, 2, 1, 3] := rfl
example : exec [.X, .R, .X] [1, 2, 3, 0, 0] = [2, 0, 1, 3, 0] := rfl
example : exec [.X, .X, .L] [1, 2, 3, 0, 0] = [2, 3, 0, 0, 1] := rfl
example : exec [.X, .X, .R] [1, 2, 3, 0, 0] = [0, 1, 2, 3, 0] := rfl
example : exec [.X, .X, .X] [1, 2, 3, 0, 0] = [2, 1, 3, 0, 0] := rfl
example : exec [.L, .L, .L, .L] [1, 2, 3, 0, 0] = [0, 1, 2, 3, 0] := rfl
example : exec [.L, .L, .L, .R] [1, 2, 3, 0, 0] = [3, 0, 0, 1, 2] := rfl
example : exec [.L, .L, .L, .X] [1, 2, 3, 0, 0] = [0, 0, 1, 2, 3] := rfl
example : exec [.L, .L, .R, .L] [1, 2, 3, 0, 0] = [3, 0, 0, 1, 2] := rfl
example : exec [.L, .L, .R, .R] [1, 2, 3, 0, 0] = [1, 2, 3, 0, 0] := rfl
example : exec [.L, .L, .R, .X] [1, 2, 3, 0, 0] = [3, 2, 0, 0, 1] := rfl
example : exec [.L, .L, .X, .L] [1, 2, 3, 0, 0] = [3, 0, 1, 2, 0] := rfl
example : exec [.L, .L, .X, .R] [1, 2, 3, 0, 0] = [2, 0, 3, 0, 1] := rfl
example : exec [.L, .L, .X, .X] [1, 2, 3, 0, 0] = [3, 0, 0, 1, 2] := rfl
example : exec [.L, .R, .L, .L] [1, 2, 3, 0, 0] = [3, 0, 0, 1, 2] := rfl
example : exec [.L, .R, .L, .R] [1, 2, 3, 0, 0] = [1, 2, 3, 0, 0] := rfl
example : exec [.L, .R, .L, .X] [1, 2, 3, 0, 0] = [3, 2, 0, 0, 1] := rfl
example : exec [.L, .R, .R, .L] [1, 2, 3, 0, 0] = [1, 2, 3, 0, 0] := rfl
example : exec [.L, .R, .R, .R] [1, 2, 3, 0, 0] = [0, 0, 1, 2, 3] := rfl
example : exec [.L, .R, .R, .X] [1, 2, 3, 0, 0] = [1, 0, 2, 3, 0] := rfl
example : exec [.L, .R, .X, .L] [1, 2, 3, 0, 0] = [1, 3, 0, 0, 2] := rfl
example : exec [.L, .R, .X, .R] [1, 2, 3, 0, 0] = [0, 2, 1, 3, 0] := rfl
example : exec [.L, .R, .X, .X] [1, 2, 3, 0, 0] = [1, 2, 3, 0, 0] := rfl
example : exec [.L, .X, .L, .L] [1, 2, 3, 0, 0] = [0, 0, 1, 3, 2] := rfl
example : exec [.L, .X, .L, .R] [1, 2, 3, 0, 0] = [3, 2, 0, 0, 1] := rfl
example : exec [.L, .X, .L, .X] [1, 2, 3, 0, 0] = [0, 2, 0, 1, 3] := rfl
example : exec [.L, .X, .R, .L] [1, 2, 3, 0, 0] = [3, 2, 0, 0, 1] := rfl
example : exec [.L, .X, .R, .R] [1, 2, 3, 0, 0] = [0, 1, 3, 2, 0] := rfl
example : exec [.L, .X, .R, .X] [1, 2, 3, 0, 0] = [3, 1, 2, 0, 0] := rfl
example : exec [.L, .X, .X, .L] [1, 2, 3, 0, 0] = [3, 0, 0, 1, 2] := rfl
example : exec [.L, .X, .X, .R] [1, 2, 3, 0, 0] = [1, 2, 3, 0, 0] := rfl
example : exec [.L, .X, .X, .X] [1, 2, 3, 0, 0] = [3, 2, 0, 0, 1] := rfl
example : exec [.R, .L, .L, .L] [1, 2, 3, 0, 0] = [3, 0, 0, 1, 2] := rfl
example : exec [.R, .L, .L, .R] [1, 2, 3, 0, 0] = [1, 2, 3, 0, 0] := rfl
example : exec [.R, .L, .L, .X] [1, 2, 3, 0, 0] = [3, 2, 0, 0, 1] := rfl
example : exec [.R, .L, .R, .L] [1, 2, 3, 0, 0] = [1, 2, 3, 0, 0] := rfl
example : exec [.R, .L, .R, .R] [1, 2, 3, 0, 0] = [0, 0, 1, 2, 3] := rfl
example : exec [.R, .L, .R, .X] [1, 2, 3, 0, 0] = [1, 0, 2, 3, 0] := rfl
example : exec [.R, .L, .X, .L] [1, 2, 3, 0, 0] = [1, 3, 0, 0, 2] := rfl
example : exec [.R, .L, .X, .R] [1, 2, 3, 0, 0] = [0, 2, 1, 3, 0] := rfl
example : exec [.R, .L, .X, .X] [1, 2, 3, 0, 0] = [1, 2, 3, 0, 0] := rfl
example : exec [.R, .R, .L, .L] [1, 2, 3, 0, 0] = [1, 2, 3, 0, 0] := rfl
example : exec [.R, .R, .L, .R] [1, 2, 3, 0, 0] = [0, 0, 1, 2, 3] := rfl
example : exec [.R, .R, .L, .X] [1, 2, 3, 0, 0] = [1, 0, 2, 3, 0] := rfl
example : exec [.R, .R, .R, .L] [1, 2, 3, 0, 0] = [0, 0, 1, 2, 3] := rfl
example : exec [.R, .R, .R, .R] [1, 2, 3, 0, 0] = [2, 3, 0, 0, 1] := rfl
example : exec [.R, .R, .R, .X] [1, 2, 3, 0, 0] = [0, 3, 0, 1, 2] := rfl
example : exec [.R, .R, .X, .L] [1, 2, 3, 0, 0] = [0, 1, 2, 3, 0] := rfl
example : exec [.R, .R, .X, .R] [1, 2, 3, 0, 0] = [3, 0, 0, 1, 2] := rfl
example : exec [.R, .R, .X, .X] [1, 2, 3, 0, 0] = [0, 0, 1, 2, 3] := rfl
example : exec [.R, .X, .L, .L] [1, 2, 3, 0, 0] = [2, 3, 0, 1, 0] := rfl
example : exec [.R, .X, .L, .R] [1, 2, 3, 0, 0] = [1, 0, 2, 3, 0] := rfl
example : exec [.R, .X, .L, .X] [1, 2, 3, 0, 0] = [2, 0, 3, 0, 1] := rfl
example : exec [.R, .X, .R, .L] [1, 2, 3, 0, 0] = [1, 0, 2, 3, 0] := rfl
example : exec [.R, .X, .R, .R] [1, 2, 3, 0, 0] = [3, 0, 1, 0, 2] := rfl
example : exec [.R, .X, .R, .X] [1, 2, 3, 0, 0] = [1, 0, 0, 2, 3] := rfl
example : exec [.R, .X, .X, .L] [1, 2, 3, 0, 0] = [1, 2, 3, 0, 0] := rfl
example : exec [.R, .X, .X, .R] [1, 2, 3, 0, 0] = [0, 0, 1, 2, 3] := rfl
example : exec [.R, .X, .X, .X] [1, 2, 3, 0, 0] = [1, 0, 2, 3, 0] := rfl
example : exec [.X, .L, .L, .L] [1, 2, 3, 0, 0] = [0, 0, 2, 1, 3] := rfl
example : exec [.X, .L, .L, .R] [1, 2, 3, 0, 0] = [1, 3, 0, 0, 2] := rfl
example : exec [.X, .L, .L, .X] [1, 2, 3, 0, 0] = [0, 3, 0, 2, 1] := rfl
example : exec [.X, .L, .R, .L] [1, 2, 3, 0, 0] = [1, 3, 0, 0, 2] := rfl
example : exec [.X, .L, .R, .R] [1, 2, 3, 0, 0] = [0, 2, 1, 3, 0] := rfl
example : exec [.X, .L, .R, .X] [1, 2, 3, 0, 0] = [1, 2, 3, 0, 0] := rfl
example : exec [.X, .L, .X, .L] [1, 2, 3, 0, 0] = [1, 0, 0, 2, 3] := rfl
example : exec [.X, .L, .X, .R] [1, 2, 3, 0, 0] = [2, 3, 1, 0, 0] := rfl
example : exec [.X, .L, .X, .X] [1, 2, 3, 0, 0] = [1, 3, 0, 0, 2] := rfl
example : exec [.X, .R, .L, .L] [1, 2, 3, 0, 0] = [1, 3, 0, 0, 2] := rfl
example : exec [.X, .R, .L, .R] [1, 2, 3, 0, 0] = [0, 2, 1, 3, 0] := rfl
example : exec [.X, .R, .L, .X] [1, 2, 3, 0, 0] = [1, 2, 3, 0, 0] := rfl
example : exec [.X, .R, .R, .L] [1, 2, 3, 0, 0] = [0, 2, 1, 3, 0] := rfl
example : exec [.X, .R, .R, .R] [1, 2, 3, 0, 0] = [3, 0, 0, 2, 1] := rfl
example : exec [.X, .R, .R, .X] [1, 2, 3, 0, 0] = [0, 0, 2, 1, 3] := rfl
example : exec [.X, .R, .X, .L] [1, 2, 3, 0, 0] = [0, 1, 3, 0, 2] := rfl
example : exec [.X, .R, .X, .R] [1, 2, 3, 0, 0] = [0, 2, 0, 1, 3] := rfl
example : exec [.X, .R, .X, .X] [1, 2, 3, 0, 0] = [0, 2, 1, 3, 0] := rfl
example : exec [.X, .X, .L, .L] [1, 2, 3, 0, 0] = [3, 0, 0, 1, 2] := rfl
example : exec [.X, .X, .L, .R] [1, 2, 3, 0, 0] = [1, 2, 3, 0, 0] := rfl
example : exec [.X, .X, .L, .X] [1, 2, 3, 0, 0] = [3, 2, 0, 0, 1] := rfl
example : exec [.X, .X, .R, .L] [1, 2, 3, 0, 0] = [1, 2, 3, 0, 0] := rfl
example : exec [.X, .X, .R, .R] [1, 2, 3, 0, 0] = [0, 0, 1, 2, 3] := rfl
example : exec [.X, .X, .R, .X] [1, 2, 3, 0, 0] = [1, 0, 2, 3, 0] := rfl
example : exec [.X, .X, .X, .L] [1, 2, 3, 0, 0] = [1, 3, 0, 0, 2] := rfl
example : exec [.X, .X, .X, .R] [1, 2, 3, 0, 0] = [0, 2, 1, 3, 0] := rfl
example : exec [.X, .X, .X, .X] [1, 2, 3, 0, 0] = [1, 2, 3, 0, 0] := rfl
example : exec [.X, .X, .R, .R, .X, .L] [0, 0, 1, 2, 3] = [2, 0, 0, 1, 3] := rfl
example : exec [.R, .L, .L, .L, .L, .L] [0, 0, 1, 2, 3] = [3, 0, 0, 1, 2] := rfl
example : exec [.L, .R, .R, .L, .L, .X] [0, 0, 1, 2, 3] = [1, 0, 2, 3, 0] := rfl
example : exec [.R, .L, .X, .L, .L, .R] [0, 0, 1, 2, 3] = [0, 1, 2, 3, 0] := rfl
example : exec [.R, .X, .L, .X, .L, .X] [0, 0, 1, 3, 2] = [1, 2, 3, 0, 0] := rfl
example : exec [.L, .L, .L, .X, .R, .R] [0, 0, 1, 3, 2] = [0, 1, 2, 3, 0] := rfl
example : exec [.X, .R, .X, .X, .X, .X] [0, 0, 1, 3, 2] = [2, 0, 0, 1, 3] := rfl
example : exec [.X, .R, .X, .R, .L, .R] [0, 0, 1, 3, 2] = [3, 0, 2, 0, 1] := rfl
example : exec [.X, .L, .R, .L, .X, .R] [0, 0, 2, 1, 3] = [0, 2, 0, 1, 3] := rfl
example : exec [.L, .X, .X, .X, .R, .X] [0, 0, 2, 1, 3] = [2, 0, 0, 1, 3] := rfl
example : exec [.L, .L, .L, .X, .R, .L] [0, 0, 2, 1, 3] = [3, 1, 0, 0, 2] := rfl
example : exec [.X, .L, .R, .X, .R, .X] [0, 0, 2, 1, 3] = [0, 3, 0, 2, 1] := rfl
example : exec [.R, .L, .R, .R, .L, .X] [0, 0, 2, 3, 1] = [0, 1, 0, 2, 3] := rfl
example : exec [.L, .R, .R, .X, .X, .R] [0, 0, 2, 3, 1] = [3, 1, 0, 0, 2] := rfl
example : exec [.L, .X, .R, .R, .R, .X] [0, 0, 2, 3, 1] = [1, 3, 0, 2, 0] := rfl
example : exec [.R, .X, .X, .X, .X, .L] [0, 0, 2, 3, 1] = [0, 0, 2, 3, 1] := rfl
example : exec [.L, .X, .R, .R, .L, .X] [0, 0, 3, 1, 2] = [3, 0, 0, 1, 2] := rfl
example : exec [.R, .X, .L, .L, .R, .X] [0, 0, 3, 1, 2] = [0, 2, 3, 1, 0] := rfl
example : exec [.L, .L, .L, .L, .X, .X] [0, 0, 3, 1, 2] = [2, 0, 0, 3, 1] := rfl
example : exec [.L, .X, .R, .R, .R, .L] [0, 0, 3, 1, 2] = [2, 0, 3, 0, 1] := rfl
example : exec [.R, .R, .X, .R, .R, .L] [0, 0, 3, 2, 1] = [3, 1, 2, 0, 0] := rfl
example : exec [.X, .L, .X, .L, .R, .R] [0, 0, 3, 2, 1] = [0, 3, 0, 2, 1] := rfl
example : exec [.R, .X, .X, .L, .X, .L] [0, 0, 3, 2, 1] = [0, 3, 2, 1, 0] := rfl
example : exec [.L, .R, .X, .L, .R, .R] [0, 0, 3, 2, 1] = [1, 0, 0, 3, 2] := rfl
example : exec [.L, .L, .L, .L, .X, .X] [0, 1, 0, 2, 3] = [3, 0, 1, 0, 2] := rfl
example : exec [.L, .R, .L, .X, .X, .X] [0, 1, 0, 2, 3] = [0, 1, 2, 3, 0] := rfl
example : exec [.X, .R, .R, .X, .R, .X] [0, 1, 0, 2, 3] = [3, 0, 2, 1, 0] := rfl
example : exec [.L, .X, .X, .R, .R, .R] [0, 1, 0, 2, 3] = [2, 3, 0, 1, 0] := rfl
example : exec [.X, .L, .L, .R, .L, .L] [0, 1, 0, 3, 2] = [3, 2, 1, 0, 0] := rfl
example : exec [.L, .X, .X, .L, .R, .X] [0, 1, 0, 3, 2] = [0, 1, 3, 2, 0] := rfl
example : exec [.L, .X, .R, .X, .L, .R] [0, 1, 0, 3, 2] = [0, 0, 1, 3, 2] := rfl
example : exec [.R, .R, .X, .L, .X, .L] [0, 1, 0, 3, 2] = [3, 1, 0, 2, 0] := rfl
example : exec [.R, .L, .L, .X, .R, .L] [0, 1, 2, 0, 3] = [2, 1, 0, 3, 0] := rfl
example : exec [.L, .L, .R, .X, .X, .X] [0, 1, 2, 0, 3] = [2, 1, 0, 3, 0] := rfl
example : exec [.X, .L, .X, .R, .R, .L] [0, 1, 2, 0, 3] = [1, 2, 0, 0, 3] := rfl
example : exec [.R, .R, .L, .L, .L, .R] [0, 1, 2, 0, 3] = [0, 1, 2, 0, 3] := rfl
example : exec [.X, .X, .R, .R, .L, .X] [0, 1, 2, 3, 0] = [0, 0, 1, 2, 3] := rfl
example : exec [.L, .L, .L, .L, .R, .X] [0, 1, 2, 3, 0] = [0, 3, 0, 1, 2] := rfl
example : exec [.L, .R, .R, .R, .R, .R] [0, 1, 2, 3, 0] = [1, 2, 3, 0, 0] := rfl
example : exec [.R, .X, .R, .R, .X, .X] [0, 1, 2, 3, 0] = [2, 3, 0, 0, 1] := rfl
example : exec [.L, .R, .R, .R, .X, .L] [0, 1, 3, 0, 2] = [0, 0, 1, 3, 2] := rfl
example : exec [.X, .X, .X, .X, .R, .L] [0, 1, 3, 0, 2] = [0, 1, 3, 0, 2] := rfl
example : exec [.R, .X, .L, .X, .X, .R] [0, 1, 3, 0, 2] = [0, 2, 1, 3, 0] := rfl
example : exec [.X, .L, .L, .X, .L, .X] [0, 1, 3, 0, 2] = [2, 3, 1, 0, 0] := rfl
example : exec [.R, .L, .R, .R, .X, .R] [0, 1, 3, 2, 0] = [3, 0, 2, 0, 1] := rfl
example : exec [.R, .X, .R, .R, .R, .X] [0, 1, 3, 2, 0] = [3, 1, 2, 0, 0] := rfl
example : exec [.R, .L, .X, .X, .L, .R] [0, 1, 3, 2, 0] = [0, 1, 3, 2, 0] := rfl
example : exec [.X, .L, .R, .X, .R, .R] [0, 1, 3, 2, 0] = [2, 0, 0, 1, 3] := rfl
example : exec [.L, .L, .L, .R, .R, .R] [0, 2, 0, 1, 3] = [0, 2, 0, 1, 3] := rfl
example : exec [.L, .R, .R, .R, .R, .X] [0, 2, 0, 1, 3] = [1, 0, 3, 0, 2] := rfl
example : exec [.R, .L, .L, .X, .X, .L] [0, 2, 0, 1, 3] = [0, 1, 3, 0, 2] := rfl
example : exec [.L, .L, .R, .R, .L, .L] [0, 2, 0, 1, 3] = [0, 1, 3, 0, 2] := rfl
example : exec [.R, .X, .X, .R, .X, .X] [0, 2, 0, 3, 1] = [3, 1, 0, 2, 0] := rfl
example : exec [.R, .L, .L, .L, .L, .X] [0, 2, 0, 3, 1] = [1, 3, 0, 2, 0] := rfl
example : exec [.L, .X, .L, .L, .R, .X] [0, 2, 0, 3, 1] = [3, 2, 1, 0, 0] := rfl
example : exec [.X, .R, .X, .R, .L, .X] [0, 2, 0, 3, 1] = [1, 2, 0, 0, 3] := rfl
example : exec [.R, .L, .X, .R, .L, .L] [0, 2, 1, 0, 3] = [0, 1, 0, 3, 2] := rfl
example : exec [.L, .R, .R, .L, .R, .X] [0, 2, 1, 0, 3] = [0, 3, 2, 1, 0] := rfl
example : exec [.X, .L, .L, .R, .R, .R] [0, 2, 1, 0, 3] = [3, 2, 0, 1, 0] := rfl
example : exec [.X, .X, .X, .R, .R, .R] [0, 2, 1, 0, 3] = [1, 0, 3, 2, 0] := rfl
example : exec [.X, .L, .X, .X, .X, .R] [0, 2, 1, 3, 0] = [2, 1, 0, 3, 0] := rfl
example : exec [.L, .X, .X, .R, .X, .R] [0, 2, 1, 3, 0] = [0, 2, 0, 1, 3] := rfl
example : exec [.L, .X, .L, .L, .R, .L] [0, 2, 1, 3, 0] = [3, 0, 0, 1, 2] := rfl
example : exec [.X, .L, .X, .X, .X, .X] [0, 2, 1, 3, 0] = [0, 1, 3, 0, 2] := rfl
example : exec [.X, .R, .R, .X, .X, .L] [0, 2, 3, 0, 1] = [1, 2, 0, 3, 0] := rfl
example : exec [.L, .X, .L, .X, .X, .X] [0, 2, 3, 0, 1] = [0, 2, 1, 0, 3] := rfl
example : exec [.R, .L, .L, .X, .R, .R] [0, 2, 3, 0, 1] = [1, 0, 3, 2, 0] := rfl
example : exec [.X, .L, .R, .R, .R, .X] [0, 2, 3, 0, 1] = [1, 0, 2, 0, 3] := rfl
example : exec [.L, .L, .L, .L, .L, .X] [0, 2, 3, 1, 0] = [2, 0, 3, 1, 0] := rfl
example : exec [.X, .L, .L, .R, .R, .R] [0, 2, 3, 1, 0] = [0, 2, 0, 3, 1] := rfl
example : exec [.R, .R, .L, .L, .L, .X] [0, 2, 3, 1, 0] = [3, 2, 1, 0, 0] := rfl
example : exec [.X, .X, .X, .X, .X, .L] [0, 2, 3, 1, 0] = [0, 3, 1, 0, 2] := rfl
example : exec [.L, .R, .R, .L, .L, .X] [0, 3, 0, 1, 2] = [0, 3, 1, 2, 0] := rfl
example : exec [.R, .R, .R, .R, .R, .X] [0, 3, 0, 1, 2] = [3, 0, 0, 1, 2] := rfl
example : exec [.X, .X, .X, .L, .R, .X] [0, 3, 0, 1, 2] = [0, 3, 0, 1, 2] := rfl
example : exec [.R, .R, .R, .R, .R, .X] [0, 3, 0, 1, 2] = [3, 0, 0, 1, 2] := rfl
example : exec [.X, .R, .R, .R, .X, .R] [0, 3, 0, 2, 1] = [0, 2, 0, 1, 3] := rfl
example : exec [.L, .L, .L, .R, .R, .L] [0, 3, 0, 2, 1] = [0, 2, 1, 0, 3] := rfl
example : exec [.L, .R, .L, .R, .X, .L] [0, 3, 0, 2, 1] = [0, 0, 2, 1, 3] := rfl
example : exec [.X, .X, .X, .X, .R, .R] [0, 3, 0, 2, 1] = [2, 1, 0, 3, 0] := rfl
example : exec [.X, .X, .X, .L, .L, .R] [0, 3, 1, 0, 2] = [0, 1, 0, 2, 3] := rfl
example : exec [.R, .L, .X, .R, .L, .L] [0, 3, 1, 0, 2] = [0, 1, 0, 2, 3] := rfl
example : exec [.X, .X, .X, .L, .R, .X] [0, 3, 1, 0, 2] = [0, 3, 1, 0, 2] := rfl
example : exec [.L, .X, .L, .X, .L, .L] [0, 3, 1, 0, 2] = [2, 0, 1, 0, 3] := rfl
example : exec [.R, .R, .R, .X, .X, .X] [0, 3, 1, 2, 0] = [2, 1, 0, 0, 3] := rfl
example : exec [.R, .X, .L, .L, .R, .R] [0, 3, 1, 2, 0] = [0, 0, 3, 1, 2] := rfl
example : exec [.X, .R, .X, .R, .L, .X] [0, 3, 1, 2, 0] = [0, 3, 0, 1, 2] := rfl
example : exec [.R, .R, .X, .R, .X, .L] [0, 3, 1, 2, 0] = [1, 2, 0, 3, 0] := rfl
example : exec [.X, .X, .L, .R, .X, .L] [0, 3, 2, 0, 1] = [0, 2, 0, 1, 3] := rfl
example : exec [.R, .X, .L, .L, .R, .X] [0, 3, 2, 0, 1] = [3, 1, 2, 0, 0] := rfl
example : exec [.X, .X, .R, .R, .R, .X] [0, 3, 2, 0, 1] = [0, 2, 1, 0, 3] := rfl
example : exec [.X, .R, .L, .R, .X, .X] [0, 3, 2, 0, 1] = [1, 3, 0, 2, 0] := rfl
example : exec [.X, .R, .R, .X, .L, .R] [0, 3, 2, 1, 0] = [0, 1, 3, 0, 2] := rfl
example : exec [.L, .X, .R, .L, .L, .X] [0, 3, 2, 1, 0] = [1, 3, 0, 0, 2] := rfl
example : exec [.R, .L, .X, .X, .R, .R] [0, 3, 2, 1, 0] = [1, 0, 0, 3, 2] := rfl
example : exec [.X, .R, .X, .X, .X, .L] [0, 3, 2, 1, 0] = [0, 0, 2, 1, 3] := rfl
example : exec [.X, .X, .L, .R, .X, .X] [1, 0, 0, 2, 3] = [1, 0, 0, 2, 3] := rfl
example : exec [.R, .X, .X, .R, .R, .L] [1, 0, 0, 2, 3] = [2, 3, 1, 0, 0] := rfl
example : exec [.X, .L, .X, .L, .X, .R] [1, 0, 0, 2, 3] = [0, 2, 1, 3, 0] := rfl
example : exec [.R, .R, .R, .R, .L, .R] [1, 0, 0, 2, 3] = [0, 0, 2, 3, 1] := rfl
example : exec [.L, .X, .L, .L, .X, .X] [1, 0, 0, 3, 2] = [3, 2, 1, 0, 0] := rfl
example : exec [.L, .X, .R, .R, .L, .X] [1, 0, 0, 3, 2] = [0, 1, 0, 3, 2] := rfl
example : exec [.R, .L, .L, .R, .L, .X] [1, 0, 0, 3, 2] = [0, 0, 3, 2, 1] := rfl
example : exec [.R, .L, .R, .L, .L, .X] [1, 0, 0, 3, 2] = [0, 0, 3, 2, 1] := rfl
example : exec [.X, .R, .R, .L, .L, .L] [1, 0, 2, 0, 3] = [1, 2, 0, 3, 0] := rfl
example : exec [.R, .L, .R, .R, .L, .R] [1, 0, 2, 0, 3] = [0, 3, 1, 0, 2] := rfl
example : exec [.R, .R, .R, .L, .L, .R] [1, 0, 2, 0, 3] = [0, 3, 1, 0, 2] := rfl
example : exec [.L, .R, .R, .X, .L, .X] [1, 0, 2, 0, 3] = [0, 3, 2, 0, 1] := rfl
example : exec [.R, .L, .L, .R, .L, .L] [1, 0, 2, 3, 0] = [2, 3, 0, 1, 0] := rfl
example : exec [.X, .L, .R, .X, .R, .X] [1, 0, 2, 3, 0] = [1, 0, 0, 2, 3] := rfl
example : exec [.L, .R, .X, .R, .X, .X] [1, 0, 2, 3, 0] = [0, 0, 1, 2, 3] := rfl
example : exec [.R, .R, .L, .L, .X, .L] [1, 0, 2, 3, 0] = [1, 2, 3, 0, 0] := rfl
example : exec [.X, .L, .R, .X, .L, .L] [1, 0, 3, 0, 2] = [3, 0, 2, 1, 0] := rfl
example : exec [.R, .L, .X, .X, .X, .X] [1, 0, 3, 0, 2] = [1, 0, 3, 0, 2] := rfl
example : exec [.R, .X, .X, .X, .X, .R] [1, 0, 3, 0, 2] = [0, 2, 1, 0, 3] := rfl
example : exec [.X, .L, .X, .R, .X, .L] [1, 0, 3, 0, 2] = [0, 1, 0, 2, 3] := rfl
example : exec [.X, .R, .X, .X, .R, .R] [1, 0, 3, 2, 0] = [3, 2, 0, 0, 1] := rfl
example : exec [.L, .R, .X, .L, .X, .R] [1, 0, 3, 2, 0] = [0, 3, 1, 2, 0] := rfl
example : exec [.R, .X, .R, .X, .R, .R] [1, 0, 3, 2, 0] = [0, 3, 1, 2, 0] := rfl
example : exec [.R, .X, .L, .L, .L, .L] [1, 0, 3, 2, 0] = [2, 1, 0, 0, 3] := rfl
example : exec [.L, .X, .X, .X, .L, .L] [1, 2, 0, 0, 3] = [0, 3, 1, 0, 2] := rfl
example : exec [.X, .L, .R, .R, .L, .X] [1, 2, 0, 0, 3] = [1, 2, 0, 0, 3] := rfl
example : exec [.L, .L, .L, .X, .L, .R] [1, 2, 0, 0, 3] = [3, 0, 1, 2, 0] := rfl
example : exec [.L, .X, .X, .X, .L, .X] [1, 2, 0, 0, 3] = [0, 2, 3, 1, 0] := rfl
example : exec [.R, .L, .R, .R, .R, .X] [1, 2, 0, 3, 0] = [3, 0, 0, 1, 2] := rfl
example : exec [.L, .L, .X, .L, .R, .X] [1, 2, 0, 3, 0] = [0, 3, 0, 1, 2] := rfl
example : exec [.R, .R, .L, .R, .L, .L] [1, 2, 0, 3, 0] = [1, 2, 0, 3, 0] := rfl
example : exec [.X, .X, .X, .R, .L, .X] [1, 2, 0, 3, 0] = [1, 2, 0, 3, 0] := rfl
example : exec [.R, .R, .L, .X, .L, .L] [1, 2, 3, 0, 0] = [2, 3, 0, 1, 0] := rfl
example : exec [.X, .R, .L, .L, .L, .X] [1, 2, 3, 0, 0] = [0, 3, 0, 2, 1] := rfl
example : exec [.L, .X, .X, .R, .X, .X] [1, 2, 3, 0, 0] = [1, 2, 3, 0, 0] := rfl
example : exec [.L, .R, .X, .L, .L, .X] [1, 2, 3, 0, 0] = [0, 3, 0, 2, 1] := rfl
example : exec [.R, .R, .L, .L, .R, .X] [1, 3, 0, 0, 2] = [1, 2, 3, 0, 0] := rfl
example : exec [.R, .R, .L, .X, .L, .L] [1, 3, 0, 0, 2] = [3, 0, 0, 1, 2] := rfl
example : exec [.X, .R, .L, .L, .R, .L] [1, 3, 0, 0, 2] = [1, 0, 0, 2, 3] := rfl
example : exec [.R, .R, .X, .R, .X, .R] [1, 3, 0, 0, 2] = [3, 2, 0, 0, 1] := rfl
example : exec [.X, .L, .L, .L, .X, .L] [1, 3, 0, 2, 0] = [2, 3, 1, 0, 0] := rfl
example : exec [.L, .R, .L, .L, .X, .R] [1, 3, 0, 2, 0] = [3, 2, 0, 0, 1] := rfl
example : exec [.X, .R, .L, .X, .R, .X] [1, 3, 0, 2, 0] = [1, 0, 3, 0, 2] := rfl
example : exec [.X, .X, .L, .R, .L, .R] [1, 3, 0, 2, 0] = [1, 3, 0, 2, 0] := rfl
example : exec [.X, .X, .L, .R, .X, .R] [1, 3, 2, 0, 0] = [0, 3, 1, 2, 0] := rfl
example : exec [.L, .R, .R, .L, .L, .R] [1, 3, 2, 0, 0] = [1, 3, 2, 0, 0] := rfl
example : exec [.X, .R, .R, .L, .X, .X] [1, 3, 2, 0, 0] = [0, 3, 1, 2, 0] := rfl
example : exec [.L, .X, .L, .L, .X, .R] [1, 3, 2, 0, 0] = [3, 0, 0, 1, 2] := rfl
example : exec [.R, .X, .R, .R, .X, .L] [2, 0, 0, 1, 3] = [0, 2, 3, 0, 1] := rfl
example : exec [.R, .R, .X, .L, .R, .X] [2, 0, 0, 1, 3] = [1, 3, 2, 0, 0] := rfl
example : exec [.L, .X, .X, .X, .X, .L] [2, 0, 0, 1, 3] = [0, 1, 3, 2, 0] := rfl
example : exec [.R, .L, .R, .R, .L, .R] [2, 0, 0, 1, 3] = [1, 3, 2, 0, 0] := rfl
example : exec [.L, .L, .X, .X, .R, .R] [2, 0, 0, 3, 1] = [2, 0, 0, 3, 1] := rfl
example : exec [.R, .R, .X, .L, .L, .L] [2, 0, 0, 3, 1] = [0, 0, 1, 3, 2] := rfl
example : exec [.L, .R, .L, .L, .L, .X] [2, 0, 0, 3, 1] = [1, 3, 2, 0, 0] := rfl
example : exec [.X, .X, .R, .R, .X, .X] [2, 0, 0, 3, 1] = [3, 1, 2, 0, 0] := rfl
example : exec [.X, .L, .L, .R, .X, .R] [2, 0, 1, 0, 3] = [0, 1, 2, 0, 3] := rfl
example : exec [.R, .X, .X, .R, .X, .L] [2, 0, 1, 0, 3] = [0, 2, 0, 1, 3] := rfl
example : exec [.X, .R, .L, .L, .R, .R] [2, 0, 1, 0, 3] = [3, 0, 2, 1, 0] := rfl
example : exec [.X, .R, .R, .R, .R, .L] [2, 0, 1, 0, 3] = [1, 0, 3, 0, 2] := rfl
example : exec [.R, .R, .L, .R, .L, .X] [2, 0, 1, 3, 0] = [2, 0, 0, 1, 3] := rfl
example : exec [.R, .X, .X, .X, .R, .R] [2, 0, 1, 3, 0] = [1, 3, 2, 0, 0] := rfl
example : exec [.X, .X, .L, .L, .R, .R] [2, 0, 1, 3, 0] = [2, 0, 1, 3, 0] := rfl
example : exec [.L, .L, .L, .X, .L, .R] [2, 0, 1, 3, 0] = [0, 3, 2, 0, 1] := rfl
example : exec [.X, .R, .R, .R, .X, .L] [2, 0, 3, 0, 1] = [3, 1, 0, 2, 0] := rfl
example : exec [.L, .X, .R, .L, .X, .L] [2, 0, 3, 0, 1] = [3, 0, 1, 2, 0] := rfl
example : exec [.L, .L, .X, .R, .L, .R] [2, 0, 3, 0, 1] = [0, 0, 3, 1, 2] := rfl
example : exec [.R, .L, .R, .R, .X, .L] [2, 0, 3, 0, 1] = [0, 2, 0, 3, 1] := rfl
example : exec [.L, .L, .R, .R, .X, .R] [2, 0, 3, 1, 0] = [0, 0, 2, 3, 1] := rfl
example : exec [.X, .R, .X, .R, .L, .X] [2, 0, 3, 1, 0] = [0, 0, 2, 3, 1] := rfl
example : exec [.L, .R, .X, .L, .R, .X] [2, 0, 3, 1, 0] = [2, 0, 3, 1, 0] := rfl
example : exec [.L, .L, .R, .R, .R, .X] [2, 0, 3, 1, 0] = [2, 0, 0, 3, 1] := rfl
example : exec [.R, .L, .X, .X, .X, .R] [2, 1, 0, 0, 3] = [3, 1, 2, 0, 0] := rfl
example : exec [.L, .X, .X, .L, .X, .L] [2, 1, 0, 0, 3] = [0, 3, 2, 1, 0] := rfl
example : exec [.R, .R, .R, .R, .L, .L] [2, 1, 0, 0, 3] = [0, 3, 2, 1, 0] := rfl
example : exec [.L, .L, .X, .L, .X, .R] [2, 1, 0, 0, 3] = [0, 3, 0, 2, 1] := rfl
example : exec [.L, .R, .X, .X, .L, .X] [2, 1, 0, 3, 0] = [0, 1, 3, 0, 2] := rfl
example : exec [.L, .R, .L, .L, .L, .X] [2, 1, 0, 3, 0] = [0, 3, 2, 1, 0] := rfl
example : exec [.X, .L, .L, .L, .R, .X] [2, 1, 0, 3, 0] = [3, 0, 0, 1, 2] := rfl
example : exec [.L, .X, .R, .R, .R, .R] [2, 1, 0, 3, 0] = [1, 3, 0, 2, 0] := rfl
example : exec [.L, .R, .L, .L, .L, .R] [2, 1, 3, 0, 0] = [3, 0, 0, 2, 1] := rfl
example : exec [.X, .L, .R, .R, .R, .X] [2, 1, 3, 0, 0] = [0, 0, 1, 2, 3] := rfl
example : exec [.L, .R, .X, .R, .R, .X] [2, 1, 3, 0, 0] = [0, 0, 1, 2, 3] := rfl
example : exec [.L, .L, .X, .L, .L, .R] [2, 1, 3, 0, 0] = [3, 0, 2, 1, 0] := rfl
example : exec [.X, .X, .L, .L, .R, .R] [2, 3, 0, 0, 1] = [2, 3, 0, 0, 1] := rfl
example : exec [.X, .L, .R, .R, .X, .R] [2, 3, 0, 0, 1] = [0, 3, 1, 2, 0] := rfl
example : exec [.L, .L, .R, .R, .R, .L] [2, 3, 0, 0, 1] = [2, 3, 0, 0, 1] := rfl
example : exec [.X, .L, .R, .X, .X, .R] [2, 3, 0, 0, 1] = [1, 3, 2, 0, 0] := rfl
example : exec [.L, .L, .L, .L, .R, .X] [2, 3, 0, 1, 0] = [0, 1, 2, 3, 0] := rfl
example : exec [.X, .X, .X, .L, .L, .L] [2, 3, 0, 1, 0] = [1, 0, 3, 2, 0] := rfl
example : exec [.X, .X, .L, .R, .L, .X] [2, 3, 0, 1, 0] = [0, 3, 1, 0, 2] := rfl
example : exec [.R, .X, .X, .X, .R, .X] [2, 3, 0, 1, 0] = [2, 1, 0, 3, 0] := rfl
example : exec [.L, .L, .L, .R, .L, .L] [2, 3, 1, 0, 0] = [0, 2, 3, 1, 0] := rfl
example : exec [.X, .L, .L, .X, .L, .R] [2, 3, 1, 0, 0] = [0, 1, 0, 3, 2] := rfl
example : exec [.R, .L, .X, .X, .R, .L] [2, 3, 1, 0, 0] = [2, 3, 1, 0, 0] := rfl
example : exec [.X, .X, .L, .L, .R, .X] [2, 3, 1, 0, 0] = [1, 3, 0, 0, 2] := rfl
example : exec [.L, .X, .L, .R, .X, .L] [3, 0, 0, 1, 2] = [0, 1, 2, 3, 0] := rfl
example : exec [.L, .L, .X, .L, .X, .X] [3, 0, 0, 1, 2] = [0, 2, 3, 0, 1] := rfl
example : exec [.L, .L, .L, .L, .R, .X] [3, 0, 0, 1, 2] = [2, 1, 3, 0, 0] := rfl
example : exec [.X, .X, .X, .X, .L, .X] [3, 0, 0, 1, 2] = [0, 0, 1, 2, 3] := rfl
example : exec [.R, .L, .X, .L, .L, .R] [3, 0, 0, 2, 1] = [3, 0, 2, 1, 0] := rfl
example : exec [.X, .L, .X, .R, .R, .L] [3, 0, 0, 2, 1] = [0, 0, 3, 2, 1] := rfl
example : exec [.R, .X, .L, .L, .X, .X] [3, 0, 0, 2, 1] = [0, 0, 2, 3, 1] := rfl
example : exec [.R, .L, .X, .L, .L, .X] [3, 0, 0, 2, 1] = [2, 0, 1, 0, 3] := rfl
example : exec [.R, .X, .X, .L, .R, .R] [3, 0, 1, 0, 2] = [0, 2, 3, 0, 1] := rfl
example : exec [.X, .L, .L, .R, .L, .X] [3, 0, 1, 0, 2] = [0, 1, 2, 0, 3] := rfl
example : exec [.R, .X, .R, .L, .L, .R] [3, 0, 1, 0, 2] = [3, 2, 0, 1, 0] := rfl
example : exec [.R, .X, .R, .R, .X, .R] [3, 0, 1, 0, 2] = [0, 0, 1, 3, 2] := rfl
example : exec [.L, .X, .L, .X, .R, .X] [3, 0, 1, 2, 0] = [2, 1, 0, 0, 3] := rfl
example : exec [.R, .X, .R, .X, .X, .L] [3, 0, 1, 2, 0] = [3, 0, 0, 1, 2] := rfl
example : exec [.R, .L, .R, .X, .X, .X] [3, 0, 1, 2, 0] = [3, 0, 0, 1, 2] := rfl
example : exec [.L, .X, .R, .L, .X, .R] [3, 0, 1, 2, 0] = [3, 0, 1, 2, 0] := rfl
example : exec [.L, .X, .L, .L, .L, .X] [3, 0, 2, 0, 1] = [3, 1, 2, 0, 0] := rfl
example : exec [.R, .X, .X, .R, .R, .L] [3, 0, 2, 0, 1] = [0, 1, 3, 0, 2] := rfl
example : exec [.X, .R, .X, .X, .R, .R] [3, 0, 2, 0, 1] = [2, 0, 1, 0, 3] := rfl
example : exec [.R, .L, .L, .L, .R, .L] [3, 0, 2, 0, 1] = [2, 0, 1, 3, 0] := rfl
example : exec [.L, .X, .R, .X, .X, .L] [3, 0, 2, 1, 0] = [2, 0, 1, 0, 3] := rfl
example : exec [.L, .L, .X, .R, .L, .R] [3, 0, 2, 1, 0] = [0, 1, 2, 0, 3] := rfl
example : exec [.X, .R, .L, .R, .X, .R] [3, 0, 2, 1, 0] = [1, 0, 0, 3, 2] := rfl
example : exec [.X, .L, .R, .X, .X, .X] [3, 0, 2, 1, 0] = [3, 0, 2, 1, 0] := rfl
example : exec [.R, .X, .X, .X, .X, .L] [3, 1, 0, 0, 2] = [3, 1, 0, 0, 2] := rfl
example : exec [.L, .L, .L, .R, .X, .L] [3, 1, 0, 0, 2] = [0, 2, 3, 1, 0] := rfl
example : exec [.L, .R, .L, .L, .R, .L] [3, 1, 0, 0, 2] = [0, 0, 2, 3, 1] := rfl
example : exec [.L, .X, .L, .R, .X, .L] [3, 1, 0, 0, 2] = [0, 0, 2, 3, 1] := rfl
example : exec [.R, .R, .L, .X, .R, .X] [3, 1, 0, 2, 0] = [3, 2, 0, 1, 0] := rfl
example : exec [.L, .R, .R, .R, .X, .X] [3, 1, 0, 2, 0] = [2, 0, 3, 1, 0] := rfl
example : exec [.X, .R, .X, .X, .R, .L] [3, 1, 0, 2, 0] = [0, 1, 3, 0, 2] := rfl
example : exec [.L, .R, .L, .L, .L, .X] [3, 1, 0, 2, 0] = [0, 2, 3, 1, 0] := rfl
example : exec [.R, .X, .L, .R, .X, .L] [3, 1, 2, 0, 0] = [3, 1, 2, 0, 0] := rfl
example : exec [.R, .R, .L, .R, .X, .X] [3, 1, 2, 0, 0] = [0, 0, 3, 1, 2] := rfl
example : exec [.R, .X, .R, .L, .X, .R] [3, 1, 2, 0, 0] = [0, 0, 3, 1, 2] := rfl
example : exec [.X, .L, .R, .R, .R, .X] [3, 1, 2, 0, 0] = [0, 0, 1, 3, 2] := rfl
example : exec [.R, .R, .R, .X, .X, .R] [3, 2, 0, 0, 1] = [2, 0, 0, 1, 3] := rfl
example : exec [.X, .L, .X, .L, .L, .X] [3, 2, 0, 0, 1] = [1, 0, 2, 0, 3] := rfl
example : exec [.R, .R, .X, .L, .X, .L] [3, 2, 0, 0, 1] = [0, 2, 0, 1, 3] := rfl
example : exec [.R, .X, .R, .L, .R, .L] [3, 2, 0, 0, 1] = [3, 1, 2, 0, 0] := rfl
example : exec [.X, .X, .X, .X, .X, .X] [3, 2, 0, 1, 0] = [3, 2, 0, 1, 0] := rfl
example : exec [.R, .X, .L, .R, .X, .L] [3, 2, 0, 1, 0] = [3, 2, 0, 1, 0] := rfl
example : exec [.R, .R, .L, .R, .R, .R] [3, 2, 0, 1, 0] = [2, 0, 1, 0, 3] := rfl
example : exec [.L, .R, .X, .L, .R, .X] [3, 2, 0, 1, 0] = [3, 2, 0, 1, 0] := rfl
example : exec [.R, .R, .R, .R, .L, .X] [3, 2, 1, 0, 0] = [0, 1, 0, 3, 2] := rfl
example : exec [.L, .X, .L, .L, .X, .L] [3, 2, 1, 0, 0] = [0, 3, 1, 2, 0] := rfl
example : exec [.L, .L, .R, .L, .R, .X] [3, 2, 1, 0, 0] = [1, 2, 0, 0, 3] := rfl
example : exec [.X, .L, .L, .X, .R, .X] [3, 2, 1, 0, 0] = [0, 3, 1, 0, 2] := rfl
example : exec [.R, .X, .R, .L, .L, .X, .L, .X] [3, 0, 1, 4, 0, 2] = [1, 2, 4, 0, 3, 0] := rfl
example : exec [.R, .X, .R, .L, .L, .X, .R, .L] [4, 1, 0, 3, 2, 0] = [1, 0, 0, 3, 2, 4] := rfl
example : exec [.R, .X, .L, .X, .R, .L, .L, .X] [4, 0, 0, 2, 1, 3] = [0, 3, 2, 1, 4, 0] := rfl
example : exec [.X, .X, .X, .R, .L, .X, .R, .X] [1, 2, 3, 4, 0, 0] = [1, 0, 2, 3, 4, 0] := rfl
example : exec [.L, .X, .R, .L, .L, .L, .X, .R] [1, 2, 4, 3, 0, 0] = [2, 0, 3, 0, 1, 4] := rfl
example : exec [.X, .R, .L, .R, .L, .L, .X, .X] [1, 2, 4, 0, 0, 3] = [1, 4, 0, 0, 3, 2] := rfl
example : exec [.L, .L, .R, .R, .R, .R, .R, .X] [4, 0, 2, 0, 3, 1] = [3, 0, 1, 4, 0, 2] := rfl
example : exec [.R, .R, .L, .L, .X, .L, .R, .X] [3, 2, 0, 1, 4, 0] = [3, 2, 0, 1, 4, 0] := rfl
example : exec [.R, .L, .R, .L, .L, .R, .L, .L] [1, 3, 0, 2, 4, 0] = [0, 2, 4, 0, 1, 3] := rfl
example : exec [.X, .X, .X, .R, .R, .L, .X, .R] [0, 1, 0, 4, 2, 3] = [2, 1, 3, 0, 0, 4] := rfl
example : exec [.R, .X, .R, .L, .R, .X, .X, .L] [0, 1, 3, 2, 0, 4] = [0, 4, 1, 3, 2, 0] := rfl
example : exec [.X, .R, .X, .X, .R, .R, .R, .L] [0, 3, 2, 0, 4, 1] = [0, 4, 1, 3, 0, 2] := rfl
example : exec [.X, .X, .R, .L, .X, .L, .X, .X] [0, 1, 0, 4, 2, 3] = [0, 0, 4, 2, 3, 1] := rfl
example : exec [.L, .L, .X, .L, .R, .R, .X, .R] [3, 0, 4, 1, 2, 0] = [3, 1, 0, 4, 2, 0] := rfl
example : exec [.R, .R, .L, .X, .L, .L, .X, .X] [1, 2, 0, 3, 4, 0] = [2, 0, 3, 4, 1, 0] := rfl
example : exec [.L, .L, .L, .L, .R, .L, .R, .L] [0, 1, 2, 4, 0, 3] = [0, 3, 0, 1, 2, 4] := rfl
example : exec [.X, .X, .R, .R, .L, .R, .L, .R] [0, 2, 0, 4, 1, 3] = [1, 3, 0, 2, 0, 4] := rfl
example : exec [.R, .X, .R, .X, .X, .L, .X, .L] [0, 4, 2, 1, 0, 3] = [0, 4, 2, 1, 0, 3] := rfl
example : exec [.R, .R, .L, .L, .X, .X, .R, .R] [0, 1, 2, 0, 3, 4] = [3, 4, 0, 1, 2, 0] := rfl
example : exec [.X, .L, .L, .R, .R, .X, .L, .X] [2, 0, 3, 0, 1, 4] = [3, 0, 0, 1, 4, 2] := rfl
example : exec [.L, .R, .X, .X, .R, .X, .L, .R] [3, 2, 1, 0, 0, 4] = [3, 4, 2, 1, 0, 0] := rfl
example : exec [.L, .X, .L, .L, .X, .R, .L, .L] [0, 2, 1, 0, 3, 4] = [0, 4, 0, 1, 2, 3] := rfl
example : exec [.R, .X, .L, .L, .X, .X, .X, .L] [4, 1, 2, 3, 0, 0] = [1, 3, 0, 4, 0, 2] := rfl
example : exec [.R, .X, .X, .R, .X, .X, .L, .R] [2, 0, 1, 4, 3, 0] = [3, 0, 2, 0, 1, 4] := rfl
example : exec [.R, .L, .L, .R, .L, .R, .L, .L] [1, 2, 4, 3, 0, 0] = [4, 3, 0, 0, 1, 2] := rfl
example : exec [.R, .R, .L, .X, .L, .L, .X, .X] [4, 3, 2, 0, 1, 0] = [3, 2, 0, 1, 4, 0] := rfl
example : exec [.L, .X, .X, .R, .X, .X, .L, .R] [1, 0, 3, 0, 2, 4] = [1, 0, 3, 0, 2, 4] := rfl
example : exec [.X, .L, .X, .R, .X, .X, .L, .R] [4, 0, 2, 0, 3, 1] = [0, 2, 4, 0, 3, 1] := rfl
example : exec [.L, .X, .L, .R, .R, .L, .R, .X] [0, 2, 4, 1, 0, 3] = [4, 0, 2, 1, 0, 3] := rfl
example : exec [.X, .L, .X, .R, .R, .L, .R, .L] [4, 0, 2, 1, 3, 0] = [0, 2, 4, 1, 3, 0] := rfl
example : exec [.L, .X, .L, .L, .R, .R, .X, .X] [0, 2, 4, 3, 1, 0] = [4, 2, 3, 1, 0, 0] := rfl
example : exec [.X, .R, .L, .L, .R, .L, .R, .R] [0, 2, 1, 4, 0, 3] = [3, 2, 0, 1, 4, 0] := rfl
example : exec [.R, .R, .R, .X, .R, .L, .X, .L] [2, 3, 1, 0, 4, 0] = [4, 0, 2, 3, 1, 0] := rfl
example : exec [.L, .L, .X, .X, .R, .L, .L, .L] [0, 0, 2, 4, 3, 1] = [3, 1, 0, 0, 2, 4] := rfl
example : exec [.L, .R, .R, .L, .L, .X, .X, .L] [1, 2, 4, 0, 0, 3] = [4, 0, 0, 3, 1, 2] := rfl
example : exec [.R, .X, .X, .X, .R, .L, .L, .L] [1, 0, 2, 0, 3, 4] = [0, 2, 0, 3, 1, 4] := rfl
example : exec [.L, .X, .R, .R, .L, .R, .L, .L] [1, 3, 2, 0, 0, 4] = [2, 3, 0, 0, 4, 1] := rfl
example : exec [.L, .X, .L, .R, .X, .R, .R, .X] [2, 3, 0, 1, 4, 0] = [2, 0, 3, 0, 1, 4] := rfl
example : exec [.X, .L, .R, .R, .R, .L, .L, .X] [3, 4, 0, 2, 1, 0] = [3, 4, 0, 2, 1, 0] := rfl
example : exec [.L, .L, .X, .X, .R, .R, .L, .R] [1, 3, 4, 2, 0, 0] = [1, 3, 4, 2, 0, 0] := rfl
example : exec [.L] [] = [] := rfl
example : exec [.R] [] = [] := rfl
example : exec [.X] [] = [] := rfl
example : exec [.L] [7] = [7] := rfl
example : exec [.R] [7] = [7] := rfl
example : exec [.X] [7] = [7] := rfl
example : root 3 2 = [1, 2, 3, 0, 0] := rfl
example : root 4 1 = [1, 2, 3, 4, 0] := rfl
example : root 1 3 = [1, 0, 0, 0] := rfl
example : root 0 0 = [] := rfl

-- Non-vacuity: the hypotheses of L2 and M7 hold on concrete data, and the
-- conclusions agree with Python's remove_zero_at on sorting words found by BFS.
example : exec [.L] [0, 1, 2, 3] = root 3 1 := rfl
example : (proj 4 0 [.L]) = ([], 3) := rfl
example : exec (proj 4 0 [.L]).1 ([0, 1, 2, 3].eraseIdx 0) = root 3 0 := rfl
example : exec [.L, .L, .X, .R] [0, 1, 3, 2] = root 3 1 := rfl
example : (proj 4 0 [.L, .L, .X, .R]) = ([.L, .X, .R], 3) := rfl
example : exec (proj 4 0 [.L, .L, .X, .R]).1 ([0, 1, 3, 2].eraseIdx 0) = root 3 0 := rfl
example : exec [.L, .X] [0, 2, 1, 3] = root 3 1 := rfl
example : (proj 4 0 [.L, .X]) = ([.X], 3) := rfl
example : exec (proj 4 0 [.L, .X]).1 ([0, 2, 1, 3].eraseIdx 0) = root 3 0 := rfl
example : exec [.R, .X, .L] [0, 2, 3, 1] = root 3 1 := rfl
example : (proj 4 0 [.R, .X, .L]) = ([.R], 3) := rfl
example : exec (proj 4 0 [.R, .X, .L]).1 ([0, 2, 3, 1].eraseIdx 0) = root 3 0 := rfl
example : exec [.X, .L, .L] [0, 3, 1, 2] = root 3 1 := rfl
example : (proj 4 0 [.X, .L, .L]) = ([.L], 3) := rfl
example : exec (proj 4 0 [.X, .L, .L]).1 ([0, 3, 1, 2].eraseIdx 0) = root 3 0 := rfl
example : exec [.X, .L, .L, .X] [0, 3, 2, 1] = root 3 1 := rfl
example : (proj 4 0 [.X, .L, .L, .X]) = ([.L, .X], 3) := rfl
example : exec (proj 4 0 [.X, .L, .L, .X]).1 ([0, 3, 2, 1].eraseIdx 0) = root 3 0 := rfl
example : exec [.L, .L] [0, 0, 1, 2, 3] = root 3 2 := rfl
example : (proj 5 0 [.L, .L]) = ([.L], 3) := rfl
example : exec (proj 5 0 [.L, .L]).1 ([0, 0, 1, 2, 3].eraseIdx 0) = root 3 1 := rfl
example : exec [.R, .R, .X, .R] [0, 0, 1, 3, 2] = root 3 2 := rfl
example : (proj 5 0 [.R, .R, .X, .R]) = ([.R, .R, .X, .R], 3) := rfl
example : exec (proj 5 0 [.R, .R, .X, .R]).1 ([0, 0, 1, 3, 2].eraseIdx 0) = root 3 1 := rfl
example : exec [.L, .L, .X] [0, 0, 2, 1, 3] = root 3 2 := rfl
example : (proj 5 0 [.L, .L, .X]) = ([.L, .X], 3) := rfl
example : exec (proj 5 0 [.L, .L, .X]).1 ([0, 0, 2, 1, 3].eraseIdx 0) = root 3 1 := rfl
example : exec [.R, .R, .X, .R, .X] [0, 0, 2, 3, 1] = root 3 2 := rfl
example : (proj 5 0 [.R, .R, .X, .R, .X]) = ([.R, .R, .X, .R, .X], 3) := rfl
example : exec (proj 5 0 [.R, .R, .X, .R, .X]).1 ([0, 0, 2, 3, 1].eraseIdx 0) = root 3 1 := rfl
example : exec [.L, .L, .X, .L, .X, .R] [0, 0, 3, 1, 2] = root 3 2 := rfl
example : (proj 5 0 [.L, .L, .X, .L, .X, .R]) = ([.L, .X, .L, .X, .R], 3) := rfl
example : exec (proj 5 0 [.L, .L, .X, .L, .X, .R]).1 ([0, 0, 3, 1, 2].eraseIdx 0) = root 3 1 := rfl
example : exec [.L, .L, .X, .L, .X, .R, .X] [0, 0, 3, 2, 1] = root 3 2 := rfl
example : (proj 5 0 [.L, .L, .X, .L, .X, .R, .X]) = ([.L, .X, .L, .X, .R, .X], 3) := rfl
example : exec (proj 5 0 [.L, .L, .X, .L, .X, .R, .X]).1 ([0, 0, 3, 2, 1].eraseIdx 0) = root 3 1 := rfl
example : exec [.L, .L] [0, 0, 1, 2] = root 2 2 := rfl
example : (proj 4 0 [.L, .L]) = ([.L], 2) := rfl
example : exec (proj 4 0 [.L, .L]).1 ([0, 0, 1, 2].eraseIdx 0) = root 2 1 := rfl
example : exec [.L, .L, .X] [0, 0, 2, 1] = root 2 2 := rfl
example : (proj 4 0 [.L, .L, .X]) = ([.L, .X], 2) := rfl
example : exec (proj 4 0 [.L, .L, .X]).1 ([0, 0, 2, 1].eraseIdx 0) = root 2 1 := rfl
example : exec [.L, .X, .L] [0, 1, 0, 2] = root 2 2 := rfl
example : (proj 4 0 [.L, .X, .L]) = ([.X, .L], 2) := rfl
example : exec (proj 4 0 [.L, .X, .L]).1 ([0, 1, 0, 2].eraseIdx 0) = root 2 1 := rfl
example : exec [.L] [0, 1, 2, 0] = root 2 2 := rfl
example : (proj 4 0 [.L]) = ([], 3) := rfl
example : exec (proj 4 0 [.L]).1 ([0, 1, 2, 0].eraseIdx 0) = root 2 1 := rfl
example : exec [.X, .R] [0, 2, 0, 1] = root 2 2 := rfl
example : (proj 4 0 [.X, .R]) = ([.R], 2) := rfl
example : exec (proj 4 0 [.X, .R]).1 ([0, 2, 0, 1].eraseIdx 0) = root 2 1 := rfl
example : exec [.L, .X] [0, 2, 1, 0] = root 2 2 := rfl
example : (proj 4 0 [.L, .X]) = ([.X], 3) := rfl
example : exec (proj 4 0 [.L, .X]).1 ([0, 2, 1, 0].eraseIdx 0) = root 2 1 := rfl
example : exec (macroZL 0) (List.replicate 1 0 ++ 5 :: [7, 8]) = [5, 0, 7, 8] := rfl
example : exec (macroLZ 0) (5 :: (List.replicate 1 0 ++ [7, 8])) = [0, 5, 7, 8] := rfl
example : exec (macroZL 1) (List.replicate 2 0 ++ 5 :: [7, 8]) = [5, 0, 0, 7, 8] := rfl
example : exec (macroLZ 1) (5 :: (List.replicate 2 0 ++ [7, 8])) = [0, 0, 5, 7, 8] := rfl
example : exec (macroZL 2) (List.replicate 3 0 ++ 5 :: [7, 8]) = [5, 0, 0, 0, 7, 8] := rfl
example : exec (macroLZ 2) (5 :: (List.replicate 3 0 ++ [7, 8])) = [0, 0, 0, 5, 7, 8] := rfl
example : exec (macroZL 3) (List.replicate 4 0 ++ 5 :: [7, 8]) = [5, 0, 0, 0, 0, 7, 8] := rfl
example : exec (macroLZ 3) (5 :: (List.replicate 4 0 ++ [7, 8])) = [0, 0, 0, 0, 5, 7, 8] := rfl

-- 473 examples
end LRX.Conformance
