"""Build PATTERNS.md from lp-raw/{canon,sym}-m<m>.json and certs-exact/m<m>.json.

Tables show LP values at Q = 1 (floats, rounded) or exact rationals (exact family).
Probes are numeric observations only; nothing here is a verified formula.
"""
import json, os, sys
from fractions import Fraction
from statistics import pstdev
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import corrcert as cc

MS = range(4, 9)


def load(fam, m):
    if fam == "exact":
        p = os.path.join(HERE, "certs-exact", f"m{m}.json")
        if not os.path.exists(p):
            return None
        c = cc.from_json(json.load(open(p)))
        Q = c["Q"]
        conv = lambda v: Fraction(v, Q)
        return {"m": m, "lambda": {k: conv(v) for k, v in c["lambda"].items()},
                "mu": {a: [conv(v) for v in vs] for a, vs in c["mu"].items()},
                **{r: {t: [conv(v) for v in vs] for t, vs in c[r].items()} for r in ("alpha", "beta", "gamma")}}
    p = os.path.join(HERE, "lp-raw", f"{fam}-m{m}.json")
    if not os.path.exists(p):
        return None
    x = json.load(open(p))["x"]
    c = cc.from_vector(m, 1, x)
    return c


def fmt(v):
    if isinstance(v, Fraction):
        return str(v)
    r = round(v, 2)
    return "0" if abs(r) < 0.005 else (f"{r:.0f}" if abs(r - round(r)) < 0.005 else f"{r:.2f}")


def table(header, rows):
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(out)


def probes(c):
    m = c["m"]
    f = float
    notes = []
    # lambda depends only on b - a?
    spread = max(pstdev([f(c["lambda"][(a, a + d)]) for a in range(m - d)]) if m - d > 1 else 0
                 for d in range(1, m))
    notes.append(f"lambda_ab spread within fixed b-a (max stdev): {spread:.3g}")
    # lambda vs min_q kappa
    gap = [f(c["lambda"][pr]) - min(cc.kappa(m, *pr, q) for q in range(1, m)) for pr in cc.pairs(m)]
    notes.append(f"lambda_ab - min_q kappa_ab(q): min {min(gap):.3g}, max {max(gap):.3g}")
    # mu linear in q?
    res = 0.0
    for a in range(m):
        ys = [f(v) for v in c["mu"][a]]
        n = len(ys); xs = list(range(1, m))
        mx, my = sum(xs) / n, sum(ys) / n
        sxx = sum((x - mx) ** 2 for x in xs)
        b1 = sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / sxx
        res = max(res, max(abs(y - (my + b1 * (x - mx))) for x, y in zip(xs, ys)))
    notes.append(f"mu_a(q) max residual from best line in q: {res:.3g}")
    # sparsity
    allv = [f(v) for r in ("alpha", "beta", "gamma") for vs in c[r].values() for v in vs]
    nz = sum(abs(v) > 1e-7 for v in allv)
    notes.append(f"triple coefficients nonzero: {nz}/{len(allv)}")
    zt = sum(all(abs(f(v)) < 1e-7 for r in ("alpha", "beta", "gamma") for v in c[r][t]) for t in cc.triples(m))
    notes.append(f"triples with all-zero alpha,beta,gamma: {zt}/{len(cc.triples(m))}")
    # triple functions depend only on gaps (b-a, c-b)?
    worst = 0.0
    groups = {}
    for t in cc.triples(m):
        groups.setdefault((t[1] - t[0], t[2] - t[1]), []).append(t)
    for ts in groups.values():
        for r in ("alpha", "beta", "gamma"):
            for q in range(m - 1):
                vals = [f(c[r][t][q]) for t in ts]
                worst = max(worst, max(vals) - min(vals))
    notes.append(f"alpha/beta/gamma max variation among triples with same (b-a, c-b): {worst:.3g}")
    return notes


def section(fam, title):
    out = [f"## {title}", ""]
    for m in MS:
        c = load(fam, m)
        if c is None:
            out += [f"### m = {m}: not available", ""]
            continue
        out += [f"### m = {m}", ""]
        out += ["Probes: " + "; ".join(probes(c)) + ".", ""]
        rows = [[str(a)] + [fmt(c["lambda"][(a, b)]) if b > a else "" for b in range(m)] for a in range(m - 1)]
        out += ["lambda_ab (row a, column b):", "", table(["a\\b"] + [str(b) for b in range(m)], rows), ""]
        rows = [[str(a)] + [fmt(v) for v in c["mu"][a]] for a in range(m)]
        out += ["mu_a(q) (row a, column q):", "", table(["a\\q"] + [str(q) for q in range(1, m)], rows), ""]
        show = sorted({(0, 1, 2), (0, 1, m - 1), (1, 2, 3), (0, m // 2, m - 1)})
        rows = [[str(t), r] + [fmt(v) for v in c[r][t]] for t in show for r in ("alpha", "beta", "gamma")]
        out += ["Triple functions (column q):", "", table(["triple", "role"] + [str(q) for q in range(1, m)], rows), ""]
    return out


def main():
    lines = ["# Coefficient patterns (corr-cert-260924, step 3)", "",
             "Generated by `patterns.py`. LP values are floats at Q = 1 from `lp-raw/`;",
             "the exact family shows exact rationals coefficient/Q. Probes are numeric",
             "observations on one LP solution each. LP solutions are not unique, so an",
             "observation can be an artefact of the solver's vertex. No formula below is",
             "claimed: a formula counts only after it re-checks exactly in `corrcert.py`.", ""]
    lines += section("exact", "Exact epsilon = 0 family (certs-exact)")
    lines += section("canon", "L1-canonical family (certs-canon)")
    lines += section("sym", "L1-canonical + reversal-symmetric family (certs-sym)")
    open(os.path.join(HERE, "PATTERNS_tables.md"), "w").write("\n".join(lines) + "\n")
    print("wrote PATTERNS_tables.md")


if __name__ == "__main__":
    main()
