"""Generate lrxlean/LrxLean/Conformance.lean from src/lrx/state.py (trusted, run once before lock).

Every example is checked by `rfl` in `lake build`, so a model definition that
disagrees with the Python model, or a statement whose hypotheses are never
satisfiable, fails the build (SPEC-track3 risk R1).
"""
from itertools import permutations, product
from pathlib import Path
import random
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from src.lrx.state import apply_L, apply_R, apply_X, canonical_root, remove_zero_at  # noqa: E402

OUT = Path(__file__).resolve().parent / "lrxlean" / "LrxLean" / "Conformance.lean"
APPLY = {"L": apply_L, "R": apply_R, "X": apply_X}


def run(word, v):
    for g in word:
        v = APPLY[g](v)
    return v


def lw(word):
    return "[" + ", ".join("." + g for g in word) + "]"


def lv(v):
    return "[" + ", ".join(map(str, v)) + "]"


def track(n, j, g):
    return {"L": n - 1 if j == 0 else j - 1, "R": 0 if j == n - 1 else j + 1, "X": 1 - j if j < 2 else j}[g]


def proj(n, j, word):
    kept = []
    for g in word:
        if {"L": j != 0, "R": j != n - 1, "X": j >= 2}[g]:
            kept.append(g)
        j = track(n, j, g)
    return "".join(kept), j


def shortest_sort(v, target, limit=12):
    frontier, seen = {v: ""}, {v}
    for _ in range(limit):
        if target in frontier:
            return frontier[target]
        nxt = {}
        for u, w in frontier.items():
            for g in "LRX":
                x = APPLY[g](u)
                if x not in seen:
                    seen.add(x)
                    nxt[x] = w + g
        frontier = nxt
    return frontier.get(target)


def main():
    rng = random.Random(260925)
    lines = ["import LrxLean.Defs", "", "/-! Generated by autoresearch/lean-loop-260925/gen_conformance.py from",
             "src/lrx/state.py (apply_L, apply_R, apply_X, canonical_root, remove_zero_at). Do not edit. -/",
             "namespace LRX.Conformance", "open LRX", ""]
    count = 0
    vectors = sorted(set(permutations((1, 2, 3, 0, 0))))
    words = ["".join(p) for k in range(0, 5) for p in product("LRX", repeat=k)]
    base = (1, 2, 3, 0, 0)
    for w in words:  # every word of length <= 4 on the root of (3,2)
        lines.append(f"example : exec {lw(w)} {lv(base)} = {lv(run(w, base))} := rfl"); count += 1
    for v in vectors:  # every vector of (3,2), 4 random words of length 6
        for _ in range(4):
            w = "".join(rng.choice("LRX") for _ in range(6))
            lines.append(f"example : exec {lw(w)} {lv(v)} = {lv(run(w, v))} := rfl"); count += 1
    for _ in range(40):  # m=4, r=2 sample, words of length 8
        v = tuple(rng.sample((1, 2, 3, 4, 0, 0), 6))
        w = "".join(rng.choice("LRX") for _ in range(8))
        lines.append(f"example : exec {lw(w)} {lv(v)} = {lv(run(w, v))} := rfl"); count += 1
    for v in [(), (7,)]:
        for g in "LRX":
            lines.append(f"example : exec {lw(g)} {lv(v)} = {lv(run(g, v))} := rfl"); count += 1
    for m, r in [(3, 2), (4, 1), (1, 3), (0, 0)]:
        lines.append(f"example : root {m} {r} = {lv(canonical_root(m, r)) if m else lv((0,) * r)} := rfl"); count += 1
    lines += ["", "-- Non-vacuity: the hypotheses of L2 and M7 hold on concrete data, and the",
              "-- conclusions agree with Python's remove_zero_at on sorting words found by BFS."]
    for m, r in [(3, 1), (3, 2), (2, 2)]:
        n, root = m + r, canonical_root(m, r)
        for v in sorted(set(permutations(root)))[:6]:
            w = shortest_sort(v, root)
            if not w:
                continue
            for j in [i for i, x in enumerate(v) if x == 0][:1]:
                pw, pj = proj(n, j, w)
                small = remove_zero_at(v, j)
                assert run(pw, small) == canonical_root(m, r - 1) and remove_zero_at(root, pj) == run(pw, small)
                lines.append(f"example : exec {lw(w)} {lv(v)} = root {m} {r} := rfl")
                lines.append(f"example : (proj {n} {j} {lw(w)}) = ({lw(pw)}, {pj}) := rfl")
                lines.append(f"example : exec (proj {n} {j} {lw(w)}).1 ({lv(v)}.eraseIdx {j}) = root {m} {r - 1} := rfl")
                count += 3
    for z in range(4):
        a, rest = 5, [7, 8]
        lines.append(f"example : exec (macroZL {z}) (List.replicate {z + 1} 0 ++ {a} :: {lv(rest)}) = "
                     f"{lv([a] + [0] * (z + 1) + rest)} := rfl")
        lines.append(f"example : exec (macroLZ {z}) ({a} :: (List.replicate {z + 1} 0 ++ {lv(rest)})) = "
                     f"{lv([0] * (z + 1) + [a] + rest)} := rfl")
        count += 2
    lines += ["", f"-- {count} examples", "end LRX.Conformance", ""]
    OUT.write_text("\n".join(lines))
    print(count, OUT)


if __name__ == "__main__":
    main()
